# Generated by Django 5.0.7 on 2024-07-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employees_remove_aboutus_employees_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='image',
            field=models.ImageField(upload_to='about_us/', verbose_name='Фото работников'),
        ),
    ]
